name: Release Published for CLI

on:
  release:
    types: [published]

env:
  PROJECT_FOLDER: '.'

jobs:
  prepare-next-dev-cycle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        ref: main
        fetch-tags: true
    - name: debugging information
      run: |
        tree . 
        git --no-pager log --decorate=short --pretty=oneline -n5
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Get pom.xml
      id: get-pom
      run: |
        POM_FILE=$PROJECT_FOLDER/pom.xml
        if [ -f $POM_FILE ]; then
          echo "pom_file=$POM_FILE" >> "$GITHUB_OUTPUT"
        else
          echo "::error::File does not exist: $POM_FILE"
          exit 1
        fi
    - name: Create next project version
      id: next-project-version
      run: | 
        echo "Using GITHUB_REF_NAME: $GITHUB_REF_NAME"
        next_version=$(./scripts/next_version.sh $GITHUB_REF_NAME)
        echo "Next project version is: $next_version"
        echo "version=$next_version" >> "$GITHUB_OUTPUT"
    - name: Set ${{ steps.get-pom.outputs.pom_file }} project version to ${{ steps.next-project-version.outputs.version }}
      env:
        NEXT_VERSION: ${{ steps.next-project-version.outputs.version }}
      run: |
        mvn --no-transfer-progress versions:set -DnewVersion=$NEXT_VERSION
    - name: add and commit
      run: |
        git config --global user.name "release-bot"
        git config --global user.email "username@users.noreply.github.com"
        git commit -am "Prepare next dev cycle ${{ steps.next-project-version.outputs.version }}"
        echo "Post commit git log"
        git --no-pager log --decorate=short --pretty=oneline -n5
        git push