name: Release Published for CLI

on:
  release:
    types: [published]

env:
  PROJECT_FOLDER: '.'
  MVN_CMD: mvn --no-transfer-progress

jobs:
  prepare-next-dev-cycle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Get pom.xml
      id: get-pom
      run: |
        POM_FILE=$PROJECT_FOLDER/pom.xml
        if [ -f $POM_FILE ]; then
          echo "pom_file=$POM_FILE" >> "$GITHUB_OUTPUT"
        else
          echo "::error::File does not exist: $POM_FILE"
          exit 1
        fi
    - name: Create next project version
      id: next-project-version
      run: | 
        next_version=$(./scripts/next_version.sh)
        echo "Next project version is: $next_version"
        echo "version=$next_version" >> "$GITHUB_OUTPUT"
    - name: Set ${{ steps.get-pom.outputs.pom_file }} project version to $${{ steps.next-project-version.outputs.version }}
      env:
        NEXT_VERSION: $${{ steps.next-project-version.outputs.version }}
      run: |
        mvn versions:set -DnewVersion=$NEXT_VERSION