name: Release Cli

on:
  workflow_call:
    inputs:
      release-version: 
        required: true
        type: string
      project-folder: 
        required: true
        type: string
      
env:
  PROJECT_FOLDER: ${{ inputs.project-folder }}
  MVN_CMD: mvn --no-transfer-progress -f ${{ inputs.project-folder }}/pom.xml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set ${{ inputs.project-folder }}/pom.xml project version to ${{ inputs.release-version }}
        run: |
          $MVN_CMD versions:set -DnewVersion=${{ inputs.release-version }}

      - name: Test and build jar
        id: test-and-build
        run: $MVN_CMD clean package

      - name: get artifactId from ${{ inputs.project-folder }}/pom.xml
        id: get_artifactId
        run: |
          artifactId=$($MVN_CMD help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          echo "artifactId=$artifactId" >> "$GITHUB_OUTPUT"

      - name: Create Release Artifact
        id: release-artifact
        env:
          ARTIFACT_NAME: ${{ steps.get_artifactId.outputs.artifactId }}-${{ inputs.release-version }}.tgz
        run: |
          echo "Artifact name: $ARTIFACT_NAME"

      - name: Create Github Release
        if: steps.test-and-build.outcome == 'success'
        uses: softprops/action-gh-release@v2
        with:
          name: Cli ${{ inputs.release-version }}
          generate_release_notes: true
          draft: true
          files: |
            ${{ env.PROJECT_FOLDER }}/target/git-tag-demo*.jar

      - name: Create Issue on Build Failure
        if: always() && failure()
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: |
            [${{ github.workflow }}] failed during [${{ github.event_name }}]

          # Auto-assign person who triggered the failure.
          assignees: ${{ github.actor }},${{ github.triggering_actor }}
          labels: CICD
          body: |
            ## Failure Report:
            
            > [!IMPORTANT]
            > Details on failed run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
            - Author: @${{ github.triggering_actor }}
            - Branch: `${{ github.ref }}`
            - Commit: ${{ github.sha }}
            - Workflow Path: `${{ github.workflow_ref }}`
    
            - [ ] **Task**: Review failed run, fix the issue(s), and re-run until successful.
