name: Release Cli

on:
  workflow_call:
    inputs:
      release-version: 
        required: true
        type: string
      project-folder: 
        required: true
        type: string
      
env:
  PROJECT_FOLDER: ${{ inputs.project-folder }}
  POM_FILE: ${{ inputs.project-folder }}/pom.xml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set ${{ inputs.project-folder }} project version to ${{ inputs.release-version }}
        run: |
          mvn versions:set -DnewVersion=${{ inputs.release-version }} -f $POM_FILE

      - name: Test and build jar
        run: mvn clean package -f $POM_FILE