name: Create Draft Release on tag

on:
  push:
    tags:
        - "cli/v*.*"

      
env:
  PROJECT_FOLDER: '.'
  # Matches cli/YYYY.MM with optional patch number using -/d
  TAG_REGEX: '^cli\/v([2-9][0-9]{3})\.Q[1-4](-[0-9])?'

jobs:
  tag-check:
    runs-on: ubuntu-latest
    outputs: 
      release-version: ${{ steps.valid-tag.outputs.release-version }}
      project-folder: ${{ env.PROJECT_FOLDER }}
    steps:
      - name: Check tag is correct
        id: valid-tag
        continue-on-error: true
        run: |
          if [[ $GITHUB_REF_NAME =~ $TAG_REGEX ]]; then
            echo "Tag name $GITHUB_REF_NAME is valid."
            # extract just the version part
            RELEASE_VERSION=$(echo $GITHUB_REF_NAME | sed 's|.*/v||')
            echo "Release version will be $RELEASE_VERSION"
            echo "release-version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
          else
            echo "Tag name $GITHUB_REF_NAME is invalid."
            exit 1
          fi

  release:
    needs: [tag-check]
    uses: ./.github/workflows/release-cli.yml
    with:
      release-version: ${{ needs.tag-check.outputs.release-version }}
      project-folder:  ${{ needs.tag-check.outputs.project-folder }}
          