name: Release Cli

on:
  workflow_call:
    inputs:
      release-version: 
        required: true
        type: string
      project-folder: 
        required: true
        type: string
      
env:
  PROJECT_FOLDER: ${{ inputs.project-folder }}
  POM_FILE: ${{ inputs.project-folder }}/pom.xml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set ${{ env.POM_FILE }} project version to ${{ inputs.release-version }}
        run: |
          mvn versions:set -DnewVersion=${{ inputs.release-version }} -f $POM_FILE

      - name: Test and build jar
        id: test-and-build
        continue-on-error: true
        run: mvn clean package -f $POM_FILE

      - name: Create Github Release
        if: steps.test-and-build.outcome == 'success'
        uses: softprops/action-gh-release@v2
        with:
          name: Cli ${{ inputs.release-version }}
          generate_release_notes: true
          draft: true
          files: |
            ${{ env.PROJECT_FOLDER }}/target/git-tag-demo*.jar

      - name: Create Issue on Build Failure
        if: steps.test-and-build.outcome == 'success'
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: |
            [${{ github.workflow }}] failed during [${{ github.event_name }}]

          # Auto-assign person who triggered the failure.
          assignees: ${{ github.actor }},${{ github.triggering_actor }}
          labels: CICD
          body: |
            ## Failure Report:
            
            > [!IMPORTANT]
            > Details on failed run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
            - Author: @${{ github.triggering_actor }}
            - Branch: `${{ github.ref }}`
            - Commit: ${{ github.sha }}
            - Workflow Path: `${{ github.workflow_ref }}`
    
            - [ ] **Task**: Review failed run, fix the issue(s), and re-run until successful.
    
            > This issue was created automatically by GitHub, 
            > through `dacbd/create-issue-action@main` action
            > and KemingHe's contribution.
            > **DO NOT** close this issue until resolved.
