name: Create Draft Release on tag

on:
  push:
    tags:
        - "cli/v*.*"

      
env:
  POM_FILE: 'cli/demo/pom.xml'
  # Matches cli/YYYY.MM with optional patch number using -/d
  TAG_REGEX: '^cli\/v([2-9][0-9]{3})\.Q[1-4](-[0-9])?'

jobs:
  tag-check:
    runs-on: ubuntu-latest
    outputs: 
      release-version: ${{ github.ref_name }}
      pom-file: ${{ env.POM_FILE }}
    steps:
      - name: Check tag is correct
        id: valid-tag
        continue-on-error: true
        run: |
          if [[ $GITHUB_REF_NAME =~ $TAG_REGEX ]]; then
            echo "Tag name is valid."
          else
            echo "Tag name $GITHUB_REF_NAME is invalid."
            exit 1
          fi

  release:
    needs: [tag-check]
    uses: ./.github/workflows/release-cli.yml
    with:
      release-version: ${{ needs.tag-check.outputs.release-version }}
      pom-file:  ${{ needs.tag-check.outputs.pom-file }}
          