name: Release Cli

on:
  workflow_call:
    inputs:
      release-version: 
        required: true
        type: string
      project-folder: 
        required: true
        type: string
      
env:
  PROJECT_FOLDER: ${{ inputs.project-folder }}
  POM_FILE: ${{ inputs.project-folder }}/pom.xml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set ${{ env.POM_FILE }} project version to ${{ inputs.release-version }}
        run: |
          mvn versions:set -DnewVersion=${{ inputs.release-version }} -f $POM_FILE

      - name: Test and build jar
        run: mvn clean package -f $POM_FILE

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ${{ env.PROJECT_FOLDER }}/target/git-tag-demo*.jar